"""add:preset father_id to MenuModel

Revision ID: 06af1b6eeef6
Revises: da442a8e6d24
Create Date: 2022-07-07 00:05:17.912893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06af1b6eeef6'
down_revision = 'da442a8e6d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('father_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'father_id')
    # ### end Alembic commands ###
