"""reinstall

Revision ID: 0b84d6822439
Revises: 5ac7c94b7dff
Create Date: 2022-07-07 01:23:50.918109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b84d6822439'
down_revision = '5ac7c94b7dff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('menu_order', sa.Integer(), nullable=False),
    sa.Column('children_ids', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'menu_id', name='uix_1')
    )
    op.create_index(op.f('ix_user_menu_id'), 'user_menu', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_menu_id'), table_name='user_menu')
    op.drop_table('user_menu')
    # ### end Alembic commands ###
