"""drop user after

Revision ID: 467b7fdf5c44
Revises: 856ad643744a
Create Date: 2022-07-18 16:40:10.566212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467b7fdf5c44'
down_revision = '856ad643744a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_menu')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
