"""modify date

Revision ID: 51b28d95e6bc
Revises: ad8f0a2c0a74
Create Date: 2022-07-05 23:52:31.672846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b28d95e6bc'
down_revision = 'ad8f0a2c0a74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
