"""drop user_menu

Revision ID: 5ac7c94b7dff
Revises: d9eb0fa92ce8
Create Date: 2022-07-07 01:22:52.663077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac7c94b7dff'
down_revision = 'd9eb0fa92ce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
