"""modify user_name to username

Revision ID: 5da7e64514fb
Revises: e1fbaea6c5c7
Create Date: 2022-07-05 00:45:20.570489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5da7e64514fb'
down_revision = 'e1fbaea6c5c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_user_name', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_user_name', 'user', ['user_name'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
