"""add:children_id

Revision ID: 73f87afc36b5
Revises: ba774ba385cc
Create Date: 2022-07-07 01:08:26.337998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f87afc36b5'
down_revision = 'ba774ba385cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('children_ids', sa.String(length=32), nullable=True))
    op.add_column('user_menu', sa.Column('children', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_menu', 'children')
    op.drop_column('menu', 'children_ids')
    # ### end Alembic commands ###
