"""message

Revision ID: 754dc0f21734
Revises: 52bedef25005
Create Date: 2022-07-04 23:35:38.785580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '754dc0f21734'
down_revision = '52bedef25005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_name', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=False),
    # sa.Column('hashed_password', sa.String(), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('is_superuser', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    # op.drop_table('account')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('account',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    # sa.Column('last_transaction_date', mysql.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_default_charset='utf8mb3',
    # mysql_engine='InnoDB'
    # )
    # op.drop_index(op.f('ix_user_user_name'), table_name='user')
    # op.drop_index(op.f('ix_user_id'), table_name='user')
    # op.drop_index(op.f('ix_user_email'), table_name='user')
    # op.drop_table('user')
    # # ### end Alembic commands ###
