"""reset:user_menu

Revision ID: 833ff1d2eb09
Revises: 06af1b6eeef6
Create Date: 2022-07-07 00:16:19.952055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833ff1d2eb09'
down_revision = '06af1b6eeef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
