"""modify date

Revision ID: a01382aae4c8
Revises: 51b28d95e6bc
Create Date: 2022-07-05 23:55:38.423535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01382aae4c8'
down_revision = '51b28d95e6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registrationDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registrationDate')
    # ### end Alembic commands ###
