"""add:children_id

Revision ID: ac8f00033a08
Revises: b65e6f177bca
Create Date: 2022-07-07 00:59:23.471039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac8f00033a08'
down_revision = 'b65e6f177bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('menu', sa.Column('children_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('menu', 'father_id')
    # op.add_column('user_menu', sa.Column('children', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('user_menu', 'father_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_menu', sa.Column('father_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_menu', 'children')
    op.add_column('menu', sa.Column('father_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'children_ids')
    # ### end Alembic commands ###
