"""add more details to user model

Revision ID: ad8f0a2c0a74
Revises: 5c37c3a08b4c
Create Date: 2022-07-05 23:42:34.823900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8f0a2c0a74'
down_revision = '5c37c3a08b4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('registrationDate', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('job', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('organization', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('introduction', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('personalWebsite', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('jobName', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('organizationName', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('locationName', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locationName')
    op.drop_column('user', 'organizationName')
    op.drop_column('user', 'jobName')
    op.drop_column('user', 'personalWebsite')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'location')
    op.drop_column('user', 'organization')
    op.drop_column('user', 'job')
    op.drop_column('user', 'role')
    op.drop_column('user', 'registrationDate')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
