"""change user role to str

Revision ID: ce032b5f0e18
Revises: 0b84d6822439
Create Date: 2022-07-08 18:04:03.644070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce032b5f0e18'
down_revision = '0b84d6822439'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_menu', 'menu_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_menu', 'menu_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
