"""add:children_id to usermenu

Revision ID: d9eb0fa92ce8
Revises: 73f87afc36b5
Create Date: 2022-07-07 01:21:46.990327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9eb0fa92ce8'
down_revision = '73f87afc36b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_menu', sa.Column('children_ids', sa.String(length=32), nullable=True))
    op.drop_column('user_menu', 'children')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_menu', sa.Column('children', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('user_menu', 'children_ids')
    # ### end Alembic commands ###
